Settings:
  # 커맨드 사용, 공지 채팅에 표시되는 접두사 입니다.
  prefix: "&f[ &a공지 &f] "

  # 공지 간격입니다. (초단위)
  interval: 30

  # 공지 랜덤 출력 여부입니다.
  random: false

  # 공지 목록
  announcements:
    - "공지를 설정해주세요."
    - "공지는 랜덤으로 출력되게할 수 있습니다."